package ventanas;

import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.UIManager;

public class Menu extends javax.swing.JFrame {

    private static Point puntoInicial = new Point();
    
    public Menu() {
        initConfig();
    }
    
    public void initConfig() {
        setUndecorated(true);
        initComponents();
        
        jPanel1.setFocusable(true);
        setResizable(false);
        setLocationRelativeTo(null);
        svgInventarios.setSVGImage("images/inventarios.svg", 180, 180);
        svgAreas.setSVGImage("images/areas.svg", 200, 200);
        moverVentanaConMouse(this, jPanel1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btnMinimizar = new javax.swing.JButton();
        svgAreas = new objetos.SVGImage();
        svgInventarios = new objetos.SVGImage();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        btnCerrar.setBackground(new java.awt.Color(0, 0, 0));
        btnCerrar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("X");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("□");
        jButton4.setEnabled(false);

        btnMinimizar.setBackground(new java.awt.Color(0, 0, 0));
        btnMinimizar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnMinimizar.setForeground(new java.awt.Color(255, 255, 255));
        btnMinimizar.setText("_");
        btnMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinimizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(btnMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        svgAreas.setForeground(new java.awt.Color(255, 255, 255));
        svgAreas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        svgAreas.setText("Áreas");
        svgAreas.setEnabled(false);
        svgAreas.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        svgAreas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        svgAreas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        svgAreas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                svgAreasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                svgAreasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                svgAreasMouseExited(evt);
            }
        });

        svgInventarios.setForeground(new java.awt.Color(255, 255, 255));
        svgInventarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        svgInventarios.setText("Inventarios");
        svgInventarios.setEnabled(false);
        svgInventarios.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        svgInventarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        svgInventarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        svgInventarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                svgInventariosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                svgInventariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                svgInventariosMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(svgInventarios, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(svgAreas, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(svgAreas, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(svgInventarios, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinimizarActionPerformed
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btnMinimizarActionPerformed

    private void svgInventariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_svgInventariosMouseEntered
        svgInventarios.setEnabled(true);
    }//GEN-LAST:event_svgInventariosMouseEntered

    private void svgInventariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_svgInventariosMouseExited
        svgInventarios.setEnabled(false);
    }//GEN-LAST:event_svgInventariosMouseExited

    private void svgAreasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_svgAreasMouseEntered
        svgAreas.setEnabled(true);
    }//GEN-LAST:event_svgAreasMouseEntered

    private void svgAreasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_svgAreasMouseExited
        svgAreas.setEnabled(false);
    }//GEN-LAST:event_svgAreasMouseExited

    private void svgInventariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_svgInventariosMouseClicked
        this.dispose();
        CrudInventarios nuevaVentana = new CrudInventarios();
        nuevaVentana.setVisible(true);
    }//GEN-LAST:event_svgInventariosMouseClicked

    private void svgAreasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_svgAreasMouseClicked
        this.dispose();
        CrudAreas nuevaVentana = new CrudAreas();
        nuevaVentana.setVisible(true);
    }//GEN-LAST:event_svgAreasMouseClicked

        private static void moverVentanaConMouse(JFrame frame, JPanel panel) {
        panel.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                puntoInicial = e.getPoint();
            }
        });
        
        panel.addMouseMotionListener(new MouseAdapter() {
            @Override
            public void mouseDragged(MouseEvent e) {
                Point pointArrastre = e.getLocationOnScreen();
                frame.setLocation(pointArrastre.x - puntoInicial.x, pointArrastre.y - puntoInicial.y);
            }
        });
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       try {
            UIManager.setLookAndFeel(new FlatDarkLaf());
        } catch (Exception e) {}
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnMinimizar;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private objetos.SVGImage svgAreas;
    private objetos.SVGImage svgInventarios;
    // End of variables declaration//GEN-END:variables
}
